<template>
  <div class="otp-input">
    <h3 class="twofa-h3">Enter your One Time Password</h3>
    <p>Enter the 6 digits code generated by your authentication app</p>
    <transition name="fade--error">
      <p v-if="error" class="error">{{ error }}</p>
    </transition>
    <form class="tac" @submit.prevent="sendTwoFactorCode">
      <input
        v-model="otp"
        v-focus
        type="text"
        maxlength="6"
        size="6"
        name="code"
        autocomplete="off"
        placeholder="000 000"
      />
      <div class="otp_submit">
        <button class="button button--invite">Validate code</button>
      </div>
    </form>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import axios from "axios";
import { useRouter } from "vue-router";
import { useStore } from "vuex";

export default defineComponent({
  name: "OtpInput",
  props: ["codeSendToUrl", "isTwoFactorEnabled"],
  setup(props, context) {
    const router = useRouter();
    const store = useStore();
    const otp = ref("");
    const error = ref("");

    //To exchange cookie or auth header w/o in every req
    axios.defaults.withCredentials = true;

    function isDigit(str: string): boolean {
      return !isNaN(Number(str));
    }

    const checkOtp = () => {
      if (otp.value.length !== 6 || !isDigit(otp.value)) {
        error.value = "Code must be 6 digits long";
      }
    };

    const sendTwoFactorCode = async () => {
      // console.log(otp.value);
      checkOtp(); // some checks over the code
      if (!error.value) {
        await axios
          .post(`http://localhost:3000/auth/2fa/${props.codeSendToUrl}`, {
            code: otp.value
          })
          .then(res => {
            // console.log(res);
            if (props.codeSendToUrl === "turn-on") {
              store.commit("toggleTwoFactor", true);
              store.dispatch("setMessage", res.data.message);
              context.emit("close");
            } else {
              router.push("account");
            }
          })
          .catch(err => (error.value = err.response.data.message));
      }
      if (error.value) {
        setTimeout(() => (error.value = ""), 2000);
      }
    };
    return {
      sendTwoFactorCode,
      otp,
      error,
    };
  }
});
</script>
<style lang="scss">
@import "../../sass/main.scss";
</style>
