/* tslint:disable */
/* eslint-disable */
/**
 * ft_transcendence API
 * Because we will nail it !
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstname: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastname: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    salt: any;
}
