/* tslint:disable */
/* eslint-disable */
/**
 * ft_transcendence API
 * Because we will nail it !
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ChannelMember
 */
export interface ChannelMember {
    /**
     * 
     * @type {number}
     * @memberof ChannelMember
     */
    channel_id: any;
    /**
     * 
     * @type {number}
     * @memberof ChannelMember
     */
    user_id: any;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelMember
     */
    is_admin: any;
}
