/* tslint:disable */
/* eslint-disable */
/**
 * ft_transcendence API
 * Because we will nail it !
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Channel
 */
export interface Channel {
    /**
     * 
     * @type {number}
     * @memberof Channel
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof Channel
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof Channel
     */
    type: any;
    /**
     * 
     * @type {string}
     * @memberof Channel
     */
    salt: any;
    /**
     * 
     * @type {string}
     * @memberof Channel
     */
    password: any;
    /**
     * 
     * @type {number}
     * @memberof Channel
     */
    ownerId: any;
    /**
     * 
     * @type {number}
     * @memberof Channel
     */
    createdAt: any;
}
