/* tslint:disable */
/* eslint-disable */
/**
 * ft_transcendence API
 * Because we will nail it !
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    id: any;
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    channel_id: any;
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    author_id: any;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    content: any;
}
